### ISSUE TITLE
Does not work for me - No companions file found

### ISSUE THREAD

**Issue by unlight** [ClementVidal/vscode-companion-file-switcher#1]
VSCode 1.5
OS: Win 8.1 x64
Project: [unlight/angular2-blank-project](/unlight/angular2-blank-project)
Extension default settings

Steps:
1. Open `home.component.html`
2. Execute `switch` command
3. Result: No companions file found.

But current directory contains `home.component.*` files
https://github.com/unlight/angular2-blank-project/tree/browserify/src/app/components/home

**Comment by ClementVidal** [comment]
By **VScode 1.5** you mean latest _insider build_  (i.e:  what's on vscode master branch) ?

**Comment by unlight** [comment]
> insider build

Yes.
![](https://i.gyazo.com/0068f52b0f780978c667d35925ed8179.png)

Also, I forgot mention that I'm using Win 8.1 x64.

**Comment by verotel** [comment]
I installed it today and it does not seem to work for me either. I understand that it finds matching files and when one such file is open and I press the shortcut (a button would be cool), it would show the other matching files, but nothing happens. Using VSCode 1.4.0

**Comment by PunchyRascal** [comment]
I installed it today and it does not seem to work for me either. I understand that it finds matching files and when one such file is open and I press the shortcut (a button would be cool), it would show the other matching files, but nothing happens. Using VSCode 1.4.0, Win 10 Pro 64bit

**Comment by ClementVidal** [comment]
It seams that the common denominator of those issues is _Windows_.
I'll try to investigate asap.
Thanks !

**Comment by PunchyRascal** [comment]
I could add that approximately 5 minutes after pressing the shortcut, the editor issues a message saying "no comapanion files found" ;) Also I work in a setup where the files are on a remote filesystem so it may take longer to scan a lot of files each time it is invoked... Maybe some caching mechanism...?

**Comment by angelfraga** [comment]
vscode.workspace.findFiles doesn't work as expected on windows returning 0 items.
Actually i m looking for  some workaround, maybe formatting the path wether window machine is detected. 🤔

**Comment by angelfraga** [comment]
Fix it in `tools.ts`

```
if (!root.endsWith('/')) {
    root = path.normalize(root + '/');
}
```

@ClementVidal  I ve created a [PR](https://github.com/ClementVidal/vscode-companion-file-switcher/pull/3) 👍

**Comment by ClementVidal** [comment]
Thanks @AngelFraga your PR has been merger, i'll ship a new version asap.
